//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFAPI.SampleServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SampleServiceReference.ISample")]
    public interface ISample {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISample/GetData", ReplyAction="http://tempuri.org/ISample/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISample/GetData", ReplyAction="http://tempuri.org/ISample/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISample/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ISample/GetDataUsingDataContractResponse")]
        WCFSample.CompositeType GetDataUsingDataContract(WCFSample.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISample/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ISample/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WCFSample.CompositeType> GetDataUsingDataContractAsync(WCFSample.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISample/GetEvenNumbers", ReplyAction="http://tempuri.org/ISample/GetEvenNumbersResponse")]
        int[] GetEvenNumbers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISample/GetEvenNumbers", ReplyAction="http://tempuri.org/ISample/GetEvenNumbersResponse")]
        System.Threading.Tasks.Task<int[]> GetEvenNumbersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISample/GetOddNumbers", ReplyAction="http://tempuri.org/ISample/GetOddNumbersResponse")]
        int[] GetOddNumbers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISample/GetOddNumbers", ReplyAction="http://tempuri.org/ISample/GetOddNumbersResponse")]
        System.Threading.Tasks.Task<int[]> GetOddNumbersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISampleChannel : WCFAPI.SampleServiceReference.ISample, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SampleClient : System.ServiceModel.ClientBase<WCFAPI.SampleServiceReference.ISample>, WCFAPI.SampleServiceReference.ISample {
        
        public SampleClient() {
        }
        
        public SampleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SampleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SampleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SampleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public WCFSample.CompositeType GetDataUsingDataContract(WCFSample.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<WCFSample.CompositeType> GetDataUsingDataContractAsync(WCFSample.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public int[] GetEvenNumbers() {
            return base.Channel.GetEvenNumbers();
        }
        
        public System.Threading.Tasks.Task<int[]> GetEvenNumbersAsync() {
            return base.Channel.GetEvenNumbersAsync();
        }
        
        public int[] GetOddNumbers() {
            return base.Channel.GetOddNumbers();
        }
        
        public System.Threading.Tasks.Task<int[]> GetOddNumbersAsync() {
            return base.Channel.GetOddNumbersAsync();
        }
    }
}
