//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFAPI.WCFClientAuth {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://checkin.ws.service.turismo5.gies.it/", ConfigurationName="WCFClientAuth.GestioneCheckinV1Impl")]
    public interface GestioneCheckinV1Impl {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WCFAPI.WCFClientAuth.inviaMovimentazioneResponse inviaMovimentazione(WCFAPI.WCFClientAuth.inviaMovimentazione request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WCFAPI.WCFClientAuth.inviaMovimentazioneResponse> inviaMovimentazioneAsync(WCFAPI.WCFClientAuth.inviaMovimentazione request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkin.ws.service.turismo5.gies.it/")]
    public partial class xmlImportDati : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codiceField;
        
        private string prodottoField;
        
        private movimentoBean[] movimentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codice {
            get {
                return this.codiceField;
            }
            set {
                this.codiceField = value;
                this.RaisePropertyChanged("codice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string prodotto {
            get {
                return this.prodottoField;
            }
            set {
                this.prodottoField = value;
                this.RaisePropertyChanged("prodotto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("movimento", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public movimentoBean[] movimento {
            get {
                return this.movimentoField;
            }
            set {
                this.movimentoField = value;
                this.RaisePropertyChanged("movimento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkin.ws.service.turismo5.gies.it/")]
    public partial class movimentoBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dataField;
        
        private strutturaBean strutturaField;
        
        private arrivoBean[] arriviField;
        
        private partenzaBean[] partenzeField;
        
        private prenotazioneBean[] prenotazioniField;
        
        private eliminazioneBean[] rettificheField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public strutturaBean struttura {
            get {
                return this.strutturaField;
            }
            set {
                this.strutturaField = value;
                this.RaisePropertyChanged("struttura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrivo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public arrivoBean[] arrivi {
            get {
                return this.arriviField;
            }
            set {
                this.arriviField = value;
                this.RaisePropertyChanged("arrivi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("partenza", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public partenzaBean[] partenze {
            get {
                return this.partenzeField;
            }
            set {
                this.partenzeField = value;
                this.RaisePropertyChanged("partenze");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("prenotazione", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public prenotazioneBean[] prenotazioni {
            get {
                return this.prenotazioniField;
            }
            set {
                this.prenotazioniField = value;
                this.RaisePropertyChanged("prenotazioni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("eliminazione", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public eliminazioneBean[] rettifiche {
            get {
                return this.rettificheField;
            }
            set {
                this.rettificheField = value;
                this.RaisePropertyChanged("rettifiche");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkin.ws.service.turismo5.gies.it/")]
    public partial class strutturaBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aperturaField;
        
        private string camereoccupateField;
        
        private string cameredisponibiliField;
        
        private string lettidisponibiliField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apertura {
            get {
                return this.aperturaField;
            }
            set {
                this.aperturaField = value;
                this.RaisePropertyChanged("apertura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string camereoccupate {
            get {
                return this.camereoccupateField;
            }
            set {
                this.camereoccupateField = value;
                this.RaisePropertyChanged("camereoccupate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cameredisponibili {
            get {
                return this.cameredisponibiliField;
            }
            set {
                this.cameredisponibiliField = value;
                this.RaisePropertyChanged("cameredisponibili");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string lettidisponibili {
            get {
                return this.lettidisponibiliField;
            }
            set {
                this.lettidisponibiliField = value;
                this.RaisePropertyChanged("lettidisponibili");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkin.ws.service.turismo5.gies.it/")]
    public partial class risultato : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idswhField;
        
        private System.Nullable<bool> successoField;
        
        private string erroreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string idswh {
            get {
                return this.idswhField;
            }
            set {
                this.idswhField = value;
                this.RaisePropertyChanged("idswh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<bool> successo {
            get {
                return this.successoField;
            }
            set {
                this.successoField = value;
                this.RaisePropertyChanged("successo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string errore {
            get {
                return this.erroreField;
            }
            set {
                this.erroreField = value;
                this.RaisePropertyChanged("errore");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkin.ws.service.turismo5.gies.it/")]
    public partial class risultatoGiorno : object, System.ComponentModel.INotifyPropertyChanged {
        
        private risultato[] arriviField;
        
        private risultato[] partenzeField;
        
        private risultato[] prenotazioniField;
        
        private risultato[] retificheField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrivo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public risultato[] arrivi {
            get {
                return this.arriviField;
            }
            set {
                this.arriviField = value;
                this.RaisePropertyChanged("arrivi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("partenza", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public risultato[] partenze {
            get {
                return this.partenzeField;
            }
            set {
                this.partenzeField = value;
                this.RaisePropertyChanged("partenze");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("prenotazione", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public risultato[] prenotazioni {
            get {
                return this.prenotazioniField;
            }
            set {
                this.prenotazioniField = value;
                this.RaisePropertyChanged("prenotazioni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("eliminazione", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public risultato[] retifiche {
            get {
                return this.retificheField;
            }
            set {
                this.retificheField = value;
                this.RaisePropertyChanged("retifiche");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkin.ws.service.turismo5.gies.it/")]
    public partial class eliminazioneBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idswhField;
        
        private string tipoalloggiatoField;
        
        private string arrivoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string idswh {
            get {
                return this.idswhField;
            }
            set {
                this.idswhField = value;
                this.RaisePropertyChanged("idswh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string tipoalloggiato {
            get {
                return this.tipoalloggiatoField;
            }
            set {
                this.tipoalloggiatoField = value;
                this.RaisePropertyChanged("tipoalloggiato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string arrivo {
            get {
                return this.arrivoField;
            }
            set {
                this.arrivoField = value;
                this.RaisePropertyChanged("arrivo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkin.ws.service.turismo5.gies.it/")]
    public partial class prenotazioneBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idswhField;
        
        private string arrivoField;
        
        private string partenzaField;
        
        private string ospitiField;
        
        private string camereField;
        
        private string prezzoField;
        
        private string canaleprenotazioneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string idswh {
            get {
                return this.idswhField;
            }
            set {
                this.idswhField = value;
                this.RaisePropertyChanged("idswh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string arrivo {
            get {
                return this.arrivoField;
            }
            set {
                this.arrivoField = value;
                this.RaisePropertyChanged("arrivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string partenza {
            get {
                return this.partenzaField;
            }
            set {
                this.partenzaField = value;
                this.RaisePropertyChanged("partenza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ospiti {
            get {
                return this.ospitiField;
            }
            set {
                this.ospitiField = value;
                this.RaisePropertyChanged("ospiti");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string camere {
            get {
                return this.camereField;
            }
            set {
                this.camereField = value;
                this.RaisePropertyChanged("camere");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string prezzo {
            get {
                return this.prezzoField;
            }
            set {
                this.prezzoField = value;
                this.RaisePropertyChanged("prezzo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string canaleprenotazione {
            get {
                return this.canaleprenotazioneField;
            }
            set {
                this.canaleprenotazioneField = value;
                this.RaisePropertyChanged("canaleprenotazione");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkin.ws.service.turismo5.gies.it/")]
    public partial class partenzaBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idswhField;
        
        private string tipoalloggiatoField;
        
        private string arrivoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string idswh {
            get {
                return this.idswhField;
            }
            set {
                this.idswhField = value;
                this.RaisePropertyChanged("idswh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string tipoalloggiato {
            get {
                return this.tipoalloggiatoField;
            }
            set {
                this.tipoalloggiatoField = value;
                this.RaisePropertyChanged("tipoalloggiato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string arrivo {
            get {
                return this.arrivoField;
            }
            set {
                this.arrivoField = value;
                this.RaisePropertyChanged("arrivo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkin.ws.service.turismo5.gies.it/")]
    public partial class arrivoBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idswhField;
        
        private string tipoalloggiatoField;
        
        private string cognomeField;
        
        private string nomeField;
        
        private string sessoField;
        
        private string cittadinanzaField;
        
        private string statoresidenzaField;
        
        private string luogoresidenzaField;
        
        private string datanascitaField;
        
        private string statonascitaField;
        
        private string comunenascitaField;
        
        private string tipoturismoField;
        
        private string mezzotrasportoField;
        
        private string canaleprenotazioneField;
        
        private string titolostudioField;
        
        private string professioneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string idswh {
            get {
                return this.idswhField;
            }
            set {
                this.idswhField = value;
                this.RaisePropertyChanged("idswh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string tipoalloggiato {
            get {
                return this.tipoalloggiatoField;
            }
            set {
                this.tipoalloggiatoField = value;
                this.RaisePropertyChanged("tipoalloggiato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string cognome {
            get {
                return this.cognomeField;
            }
            set {
                this.cognomeField = value;
                this.RaisePropertyChanged("cognome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string sesso {
            get {
                return this.sessoField;
            }
            set {
                this.sessoField = value;
                this.RaisePropertyChanged("sesso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string cittadinanza {
            get {
                return this.cittadinanzaField;
            }
            set {
                this.cittadinanzaField = value;
                this.RaisePropertyChanged("cittadinanza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string statoresidenza {
            get {
                return this.statoresidenzaField;
            }
            set {
                this.statoresidenzaField = value;
                this.RaisePropertyChanged("statoresidenza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string luogoresidenza {
            get {
                return this.luogoresidenzaField;
            }
            set {
                this.luogoresidenzaField = value;
                this.RaisePropertyChanged("luogoresidenza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string datanascita {
            get {
                return this.datanascitaField;
            }
            set {
                this.datanascitaField = value;
                this.RaisePropertyChanged("datanascita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string statonascita {
            get {
                return this.statonascitaField;
            }
            set {
                this.statonascitaField = value;
                this.RaisePropertyChanged("statonascita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string comunenascita {
            get {
                return this.comunenascitaField;
            }
            set {
                this.comunenascitaField = value;
                this.RaisePropertyChanged("comunenascita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public string tipoturismo {
            get {
                return this.tipoturismoField;
            }
            set {
                this.tipoturismoField = value;
                this.RaisePropertyChanged("tipoturismo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public string mezzotrasporto {
            get {
                return this.mezzotrasportoField;
            }
            set {
                this.mezzotrasportoField = value;
                this.RaisePropertyChanged("mezzotrasporto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public string canaleprenotazione {
            get {
                return this.canaleprenotazioneField;
            }
            set {
                this.canaleprenotazioneField = value;
                this.RaisePropertyChanged("canaleprenotazione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=14)]
        public string titolostudio {
            get {
                return this.titolostudioField;
            }
            set {
                this.titolostudioField = value;
                this.RaisePropertyChanged("titolostudio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=15)]
        public string professione {
            get {
                return this.professioneField;
            }
            set {
                this.professioneField = value;
                this.RaisePropertyChanged("professione");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="inviaMovimentazione", WrapperNamespace="http://checkin.ws.service.turismo5.gies.it/", IsWrapped=true)]
    public partial class inviaMovimentazione {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://checkin.ws.service.turismo5.gies.it/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WCFAPI.WCFClientAuth.xmlImportDati movimentazione;
        
        public inviaMovimentazione() {
        }
        
        public inviaMovimentazione(WCFAPI.WCFClientAuth.xmlImportDati movimentazione) {
            this.movimentazione = movimentazione;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="inviaMovimentazioneResponse", WrapperNamespace="http://checkin.ws.service.turismo5.gies.it/", IsWrapped=true)]
    public partial class inviaMovimentazioneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://checkin.ws.service.turismo5.gies.it/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("risultatiGiorno", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WCFAPI.WCFClientAuth.risultatoGiorno[] @return;
        
        public inviaMovimentazioneResponse() {
        }
        
        public inviaMovimentazioneResponse(WCFAPI.WCFClientAuth.risultatoGiorno[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GestioneCheckinV1ImplChannel : WCFAPI.WCFClientAuth.GestioneCheckinV1Impl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestioneCheckinV1ImplClient : System.ServiceModel.ClientBase<WCFAPI.WCFClientAuth.GestioneCheckinV1Impl>, WCFAPI.WCFClientAuth.GestioneCheckinV1Impl {
        
        public GestioneCheckinV1ImplClient() {
        }
        
        public GestioneCheckinV1ImplClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestioneCheckinV1ImplClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestioneCheckinV1ImplClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestioneCheckinV1ImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFAPI.WCFClientAuth.inviaMovimentazioneResponse WCFAPI.WCFClientAuth.GestioneCheckinV1Impl.inviaMovimentazione(WCFAPI.WCFClientAuth.inviaMovimentazione request) {
            return base.Channel.inviaMovimentazione(request);
        }
        
        public WCFAPI.WCFClientAuth.risultatoGiorno[] inviaMovimentazione(WCFAPI.WCFClientAuth.xmlImportDati movimentazione) {
            WCFAPI.WCFClientAuth.inviaMovimentazione inValue = new WCFAPI.WCFClientAuth.inviaMovimentazione();
            inValue.movimentazione = movimentazione;
            WCFAPI.WCFClientAuth.inviaMovimentazioneResponse retVal = ((WCFAPI.WCFClientAuth.GestioneCheckinV1Impl)(this)).inviaMovimentazione(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCFAPI.WCFClientAuth.inviaMovimentazioneResponse> WCFAPI.WCFClientAuth.GestioneCheckinV1Impl.inviaMovimentazioneAsync(WCFAPI.WCFClientAuth.inviaMovimentazione request) {
            return base.Channel.inviaMovimentazioneAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCFAPI.WCFClientAuth.inviaMovimentazioneResponse> inviaMovimentazioneAsync(WCFAPI.WCFClientAuth.xmlImportDati movimentazione) {
            WCFAPI.WCFClientAuth.inviaMovimentazione inValue = new WCFAPI.WCFClientAuth.inviaMovimentazione();
            inValue.movimentazione = movimentazione;
            return ((WCFAPI.WCFClientAuth.GestioneCheckinV1Impl)(this)).inviaMovimentazioneAsync(inValue);
        }
    }
}
