//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFAPI.WCFAsyncServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFAsyncServiceReference.IWCFAsync")]
    public interface IWCFAsync {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAsync/GetData", ReplyAction="http://tempuri.org/IWCFAsync/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAsync/GetData", ReplyAction="http://tempuri.org/IWCFAsync/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAsync/Get", ReplyAction="http://tempuri.org/IWCFAsync/GetResponse")]
        string Get(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAsync/Get", ReplyAction="http://tempuri.org/IWCFAsync/GetResponse")]
        System.Threading.Tasks.Task<string> GetAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAsync/GetSync", ReplyAction="http://tempuri.org/IWCFAsync/GetSyncResponse")]
        string GetSync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAsync/GetSync", ReplyAction="http://tempuri.org/IWCFAsync/GetSyncResponse")]
        System.Threading.Tasks.Task<string> GetSyncAsync(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFAsyncChannel : WCFAPI.WCFAsyncServiceReference.IWCFAsync, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFAsyncClient : System.ServiceModel.ClientBase<WCFAPI.WCFAsyncServiceReference.IWCFAsync>, WCFAPI.WCFAsyncServiceReference.IWCFAsync {
        
        public WCFAsyncClient() {
        }
        
        public WCFAsyncClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFAsyncClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFAsyncClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFAsyncClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public string Get(int value) {
            return base.Channel.Get(value);
        }
        
        public System.Threading.Tasks.Task<string> GetAsync(int value) {
            return base.Channel.GetAsync(value);
        }
        
        public string GetSync(int value) {
            return base.Channel.GetSync(value);
        }
        
        public System.Threading.Tasks.Task<string> GetSyncAsync(int value) {
            return base.Channel.GetSyncAsync(value);
        }
    }
}
