//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFAPI.DbOperationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WCFDb")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DbOperationService.IDbOperation")]
    public interface IDbOperation {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbOperation/UpdateTable", ReplyAction="http://tempuri.org/IDbOperation/UpdateTableResponse")]
        bool UpdateTable(int id, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbOperation/UpdateTable", ReplyAction="http://tempuri.org/IDbOperation/UpdateTableResponse")]
        System.Threading.Tasks.Task<bool> UpdateTableAsync(int id, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbOperation/GetData", ReplyAction="http://tempuri.org/IDbOperation/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbOperation/GetData", ReplyAction="http://tempuri.org/IDbOperation/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbOperation/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IDbOperation/GetDataUsingDataContractResponse")]
        WCFAPI.DbOperationService.CompositeType GetDataUsingDataContract(WCFAPI.DbOperationService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbOperation/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IDbOperation/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WCFAPI.DbOperationService.CompositeType> GetDataUsingDataContractAsync(WCFAPI.DbOperationService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbOperation/GetTable", ReplyAction="http://tempuri.org/IDbOperation/GetTableResponse")]
        System.Data.DataTable GetTable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbOperation/GetTable", ReplyAction="http://tempuri.org/IDbOperation/GetTableResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetTableAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbOperation/GetTableFromPro", ReplyAction="http://tempuri.org/IDbOperation/GetTableFromProResponse")]
        System.Data.DataTable GetTableFromPro();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbOperation/GetTableFromPro", ReplyAction="http://tempuri.org/IDbOperation/GetTableFromProResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetTableFromProAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDbOperationChannel : WCFAPI.DbOperationService.IDbOperation, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DbOperationClient : System.ServiceModel.ClientBase<WCFAPI.DbOperationService.IDbOperation>, WCFAPI.DbOperationService.IDbOperation {
        
        public DbOperationClient() {
        }
        
        public DbOperationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DbOperationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DbOperationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DbOperationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool UpdateTable(int id, string userName) {
            return base.Channel.UpdateTable(id, userName);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateTableAsync(int id, string userName) {
            return base.Channel.UpdateTableAsync(id, userName);
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public WCFAPI.DbOperationService.CompositeType GetDataUsingDataContract(WCFAPI.DbOperationService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<WCFAPI.DbOperationService.CompositeType> GetDataUsingDataContractAsync(WCFAPI.DbOperationService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public System.Data.DataTable GetTable() {
            return base.Channel.GetTable();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetTableAsync() {
            return base.Channel.GetTableAsync();
        }
        
        public System.Data.DataTable GetTableFromPro() {
            return base.Channel.GetTableFromPro();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetTableFromProAsync() {
            return base.Channel.GetTableFromProAsync();
        }
    }
}
