//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WCFAPI.WCFAuthAsmx {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GestioneCheckinV1ImplServiceSoapBinding", Namespace="http://checkin.ws.service.turismo5.gies.it/")]
    public partial class GestioneCheckinV1ImplService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback inviaMovimentazioneOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GestioneCheckinV1ImplService() {
            this.Url = global::WCFAPI.Properties.Settings.Default.WCFAPI_WCFAuthAsmx_GestioneCheckinV1ImplService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event inviaMovimentazioneCompletedEventHandler inviaMovimentazioneCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://checkin.ws.service.turismo5.gies.it/", ResponseNamespace="http://checkin.ws.service.turismo5.gies.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("risultatiGiorno", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public risultatoGiorno[] inviaMovimentazione([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] xmlImportDati movimentazione) {
            object[] results = this.Invoke("inviaMovimentazione", new object[] {
                        movimentazione});
            return ((risultatoGiorno[])(results[0]));
        }
        
        /// <remarks/>
        public void inviaMovimentazioneAsync(xmlImportDati movimentazione) {
            this.inviaMovimentazioneAsync(movimentazione, null);
        }
        
        /// <remarks/>
        public void inviaMovimentazioneAsync(xmlImportDati movimentazione, object userState) {
            if ((this.inviaMovimentazioneOperationCompleted == null)) {
                this.inviaMovimentazioneOperationCompleted = new System.Threading.SendOrPostCallback(this.OninviaMovimentazioneOperationCompleted);
            }
            this.InvokeAsync("inviaMovimentazione", new object[] {
                        movimentazione}, this.inviaMovimentazioneOperationCompleted, userState);
        }
        
        private void OninviaMovimentazioneOperationCompleted(object arg) {
            if ((this.inviaMovimentazioneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.inviaMovimentazioneCompleted(this, new inviaMovimentazioneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkin.ws.service.turismo5.gies.it/")]
    public partial class xmlImportDati {
        
        private string codiceField;
        
        private string prodottoField;
        
        private movimentoBean[] movimentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codice {
            get {
                return this.codiceField;
            }
            set {
                this.codiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string prodotto {
            get {
                return this.prodottoField;
            }
            set {
                this.prodottoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("movimento", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public movimentoBean[] movimento {
            get {
                return this.movimentoField;
            }
            set {
                this.movimentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkin.ws.service.turismo5.gies.it/")]
    public partial class movimentoBean {
        
        private string dataField;
        
        private strutturaBean strutturaField;
        
        private arrivoBean[] arriviField;
        
        private partenzaBean[] partenzeField;
        
        private prenotazioneBean[] prenotazioniField;
        
        private eliminazioneBean[] rettificheField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public strutturaBean struttura {
            get {
                return this.strutturaField;
            }
            set {
                this.strutturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrivo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public arrivoBean[] arrivi {
            get {
                return this.arriviField;
            }
            set {
                this.arriviField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("partenza", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public partenzaBean[] partenze {
            get {
                return this.partenzeField;
            }
            set {
                this.partenzeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("prenotazione", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public prenotazioneBean[] prenotazioni {
            get {
                return this.prenotazioniField;
            }
            set {
                this.prenotazioniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("eliminazione", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public eliminazioneBean[] rettifiche {
            get {
                return this.rettificheField;
            }
            set {
                this.rettificheField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkin.ws.service.turismo5.gies.it/")]
    public partial class strutturaBean {
        
        private string aperturaField;
        
        private string camereoccupateField;
        
        private string cameredisponibiliField;
        
        private string lettidisponibiliField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apertura {
            get {
                return this.aperturaField;
            }
            set {
                this.aperturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string camereoccupate {
            get {
                return this.camereoccupateField;
            }
            set {
                this.camereoccupateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cameredisponibili {
            get {
                return this.cameredisponibiliField;
            }
            set {
                this.cameredisponibiliField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lettidisponibili {
            get {
                return this.lettidisponibiliField;
            }
            set {
                this.lettidisponibiliField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkin.ws.service.turismo5.gies.it/")]
    public partial class risultato {
        
        private string idswhField;
        
        private System.Nullable<bool> successoField;
        
        private string erroreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idswh {
            get {
                return this.idswhField;
            }
            set {
                this.idswhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<bool> successo {
            get {
                return this.successoField;
            }
            set {
                this.successoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string errore {
            get {
                return this.erroreField;
            }
            set {
                this.erroreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkin.ws.service.turismo5.gies.it/")]
    public partial class risultatoGiorno {
        
        private risultato[] arriviField;
        
        private risultato[] partenzeField;
        
        private risultato[] prenotazioniField;
        
        private risultato[] retificheField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrivo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public risultato[] arrivi {
            get {
                return this.arriviField;
            }
            set {
                this.arriviField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("partenza", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public risultato[] partenze {
            get {
                return this.partenzeField;
            }
            set {
                this.partenzeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("prenotazione", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public risultato[] prenotazioni {
            get {
                return this.prenotazioniField;
            }
            set {
                this.prenotazioniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("eliminazione", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public risultato[] retifiche {
            get {
                return this.retificheField;
            }
            set {
                this.retificheField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkin.ws.service.turismo5.gies.it/")]
    public partial class eliminazioneBean {
        
        private string idswhField;
        
        private string tipoalloggiatoField;
        
        private string arrivoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idswh {
            get {
                return this.idswhField;
            }
            set {
                this.idswhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoalloggiato {
            get {
                return this.tipoalloggiatoField;
            }
            set {
                this.tipoalloggiatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arrivo {
            get {
                return this.arrivoField;
            }
            set {
                this.arrivoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkin.ws.service.turismo5.gies.it/")]
    public partial class prenotazioneBean {
        
        private string idswhField;
        
        private string arrivoField;
        
        private string partenzaField;
        
        private string ospitiField;
        
        private string camereField;
        
        private string prezzoField;
        
        private string canaleprenotazioneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idswh {
            get {
                return this.idswhField;
            }
            set {
                this.idswhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arrivo {
            get {
                return this.arrivoField;
            }
            set {
                this.arrivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string partenza {
            get {
                return this.partenzaField;
            }
            set {
                this.partenzaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ospiti {
            get {
                return this.ospitiField;
            }
            set {
                this.ospitiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string camere {
            get {
                return this.camereField;
            }
            set {
                this.camereField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string prezzo {
            get {
                return this.prezzoField;
            }
            set {
                this.prezzoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string canaleprenotazione {
            get {
                return this.canaleprenotazioneField;
            }
            set {
                this.canaleprenotazioneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkin.ws.service.turismo5.gies.it/")]
    public partial class partenzaBean {
        
        private string idswhField;
        
        private string tipoalloggiatoField;
        
        private string arrivoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idswh {
            get {
                return this.idswhField;
            }
            set {
                this.idswhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoalloggiato {
            get {
                return this.tipoalloggiatoField;
            }
            set {
                this.tipoalloggiatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arrivo {
            get {
                return this.arrivoField;
            }
            set {
                this.arrivoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://checkin.ws.service.turismo5.gies.it/")]
    public partial class arrivoBean {
        
        private string idswhField;
        
        private string tipoalloggiatoField;
        
        private string cognomeField;
        
        private string nomeField;
        
        private string sessoField;
        
        private string cittadinanzaField;
        
        private string statoresidenzaField;
        
        private string luogoresidenzaField;
        
        private string datanascitaField;
        
        private string statonascitaField;
        
        private string comunenascitaField;
        
        private string tipoturismoField;
        
        private string mezzotrasportoField;
        
        private string canaleprenotazioneField;
        
        private string titolostudioField;
        
        private string professioneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idswh {
            get {
                return this.idswhField;
            }
            set {
                this.idswhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoalloggiato {
            get {
                return this.tipoalloggiatoField;
            }
            set {
                this.tipoalloggiatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string cognome {
            get {
                return this.cognomeField;
            }
            set {
                this.cognomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sesso {
            get {
                return this.sessoField;
            }
            set {
                this.sessoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cittadinanza {
            get {
                return this.cittadinanzaField;
            }
            set {
                this.cittadinanzaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string statoresidenza {
            get {
                return this.statoresidenzaField;
            }
            set {
                this.statoresidenzaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string luogoresidenza {
            get {
                return this.luogoresidenzaField;
            }
            set {
                this.luogoresidenzaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string datanascita {
            get {
                return this.datanascitaField;
            }
            set {
                this.datanascitaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string statonascita {
            get {
                return this.statonascitaField;
            }
            set {
                this.statonascitaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string comunenascita {
            get {
                return this.comunenascitaField;
            }
            set {
                this.comunenascitaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string tipoturismo {
            get {
                return this.tipoturismoField;
            }
            set {
                this.tipoturismoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string mezzotrasporto {
            get {
                return this.mezzotrasportoField;
            }
            set {
                this.mezzotrasportoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string canaleprenotazione {
            get {
                return this.canaleprenotazioneField;
            }
            set {
                this.canaleprenotazioneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string titolostudio {
            get {
                return this.titolostudioField;
            }
            set {
                this.titolostudioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string professione {
            get {
                return this.professioneField;
            }
            set {
                this.professioneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void inviaMovimentazioneCompletedEventHandler(object sender, inviaMovimentazioneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class inviaMovimentazioneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal inviaMovimentazioneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public risultatoGiorno[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((risultatoGiorno[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591