//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFDb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASConfigurationPropertiesTable
    {
        public int Id { get; set; }
        public string ArchiveServer { get; set; }
        public string ArchiveDatabase { get; set; }
        public Nullable<long> MaxSizeFailedStagingTable { get; set; }
        public bool APEnabled { get; set; }
        public Nullable<int> APThreshold { get; set; }
        public Nullable<double> APMaxEventAge { get; set; }
        public Nullable<int> APTrimPercentage { get; set; }
    }
}
