//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFDb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASEventSourcesTable
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Computer { get; set; }
        public string Site { get; set; }
        public string VirtualPath { get; set; }
        public string ApplicationVirtualPath { get; set; }
        public string ServiceVirtualPath { get; set; }
    }
}
