//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFDb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASJobsTable
    {
        public int Id { get; set; }
        public string JobIdentifier { get; set; }
        public string Sql { get; set; }
        public Nullable<System.DateTime> LastRunTime { get; set; }
        public Nullable<bool> IsLastRunSuccess { get; set; }
        public Nullable<int> LastErrorCode { get; set; }
        public string LastError { get; set; }
        public Nullable<int> PeriodInSeconds { get; set; }
        public Nullable<System.Guid> ConversationHandle { get; set; }
    }
}
