//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFDb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASTransferEventsTable
    {
        public long Id { get; set; }
        public int EventTypeId { get; set; }
        public int EventSourceId { get; set; }
        public int ProcessId { get; set; }
        public byte TraceLevelId { get; set; }
        public string E2EActivityId { get; set; }
        public string ToE2EActivityId { get; set; }
        public System.DateTime TimeCreated { get; set; }
    }
}
