//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFDb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASWfEventAnnotationSetsTable
    {
        public int Id { get; set; }
        public string Annotations { get; set; }
        public int AnnotationsChecksum { get; set; }
    }
}
