//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFDb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASWfEventPropertiesTable
    {
        public long EventId { get; set; }
        public byte WfDataSourceId { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string ValueBlob { get; set; }
        public System.DateTime TimeCreated { get; set; }
    }
}
