//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFDb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASWfEventsTable
    {
        public long Id { get; set; }
        public int EventTypeId { get; set; }
        public int EventSourceId { get; set; }
        public int ProcessId { get; set; }
        public byte TraceLevelId { get; set; }
        public string WorkflowInstanceId { get; set; }
        public Nullable<long> RecordNumber { get; set; }
        public Nullable<int> TrackingProfileId { get; set; }
        public Nullable<int> AnnotationSetId { get; set; }
        public System.DateTime TimeCreated { get; set; }
        public string Data1Str { get; set; }
        public string Data2Str { get; set; }
        public string Data3Str { get; set; }
        public string Data4Str { get; set; }
        public string Data5Str { get; set; }
        public string Data6Str { get; set; }
        public string Data7Str { get; set; }
        public string Data8Str { get; set; }
        public string Data1MaxStr { get; set; }
        public Nullable<int> Data1Int { get; set; }
    }
}
