//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFDb.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestDbEntities : DbContext
    {
        public TestDbEntities()
            : base("name=TestDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ASConfigurationPropertiesTable> ASConfigurationPropertiesTables { get; set; }
        public DbSet<ASEventSourcesTable> ASEventSourcesTables { get; set; }
        public DbSet<ASFailedStagingTable> ASFailedStagingTables { get; set; }
        public DbSet<ASJobsTable> ASJobsTables { get; set; }
        public DbSet<ASOperationsHistoryTable> ASOperationsHistoryTables { get; set; }
        public DbSet<ASWfEventAnnotationSetsTable> ASWfEventAnnotationSetsTables { get; set; }
        public DbSet<ASWfEventAnnotationsTable> ASWfEventAnnotationsTables { get; set; }
        public DbSet<ASWfTrackingProfilesTable> ASWfTrackingProfilesTables { get; set; }
        public DbSet<ASDBVersionTable> ASDBVersionTables { get; set; }
        public DbSet<ASStagingTable> ASStagingTables { get; set; }
        public DbSet<ASTransferEventsTable> ASTransferEventsTables { get; set; }
        public DbSet<ASWcfEventsTable> ASWcfEventsTables { get; set; }
        public DbSet<ASWfEventPropertiesTable> ASWfEventPropertiesTables { get; set; }
        public DbSet<ASWfEventsTable> ASWfEventsTables { get; set; }
        public DbSet<ASWfInstancesTable> ASWfInstancesTables { get; set; }
        public DbSet<ASWfPropertyNamesTable> ASWfPropertyNamesTables { get; set; }
        public DbSet<tblUser> tblUsers { get; set; }
    }
}
