//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFAPI.WCFDebugBehaviorReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFDebugBehaviorReference.IWCFDebugBehavior")]
    public interface IWCFDebugBehavior {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFDebugBehavior/GetData", ReplyAction="http://tempuri.org/IWCFDebugBehavior/GetDataResponse")]
        string GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFDebugBehavior/GetData", ReplyAction="http://tempuri.org/IWCFDebugBehavior/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFDebugBehaviorChannel : WCFAPI.WCFDebugBehaviorReference.IWCFDebugBehavior, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFDebugBehaviorClient : System.ServiceModel.ClientBase<WCFAPI.WCFDebugBehaviorReference.IWCFDebugBehavior>, WCFAPI.WCFDebugBehaviorReference.IWCFDebugBehavior {
        
        public WCFDebugBehaviorClient() {
        }
        
        public WCFDebugBehaviorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFDebugBehaviorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFDebugBehaviorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFDebugBehaviorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData() {
            return base.Channel.GetData();
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync() {
            return base.Channel.GetDataAsync();
        }
    }
}
